### ISSUE TITLE
Fontbakery reports fails with static font names

### ISSUE THREAD

**Issue by jenskutilek** [jenskutilek/homecomputer-fonts#23]
| nameID | current | expected | 
| :--- | :--- | :--- | 
| Family Name | Sixtyfour Touching | Sixtyfour Touching |
 | Subfamily Name | Regular | Regular | 
| Full Name | Sixtyfour Touching | Sixtyfour Touching Regular | 
| Poscript Name | Sixtyfour-Touching | SixtyfourTouching-Regular | 
| Typographic Family Name | Sixtyfour | N/A |
 | Typographic Subfamily Name | Touching | N/A |

... and the same for all other styles except "Close", which is different:

| nameID | current | expected |
 | :--- | :--- | :--- | 
| Family Name | Sixtyfour Close | Sixtyfour | 
| Subfamily Name | Regular | Regular |
 | Full Name | Sixtyfour Close | Sixtyfour Regular | 
| Poscript Name | Sixtyfour-Close | Sixtyfour-Regular | 
| Typographic Family Name | Sixtyfour | N/A | 
| Typographic Subfamily Name | Close | N/A |

**Comment by vv-monsalve** [comment]
I didn't receive this Fail on my end. I'll investigate about this.

**Comment by vv-monsalve** [comment]
Hi @jenskutilek, I've filed a new issue in gftools so this fix gets included for static fonts of only custom axis families.

This could be fixed with the `gtools fix-nameids` tool. I could create a PR with this fix, or you would like to include a step for this in the make file. Let me know what would you prefer.

Now, an important notice is we are not including static instances for fonts with only custom axes.  The .zip file the UI will produce will only include the VF plus a single static for the Regular instance. You can offer the backup static fonts here in the upstream repository.

**Comment by vv-monsalve** [comment]
@jenskutilek this issue can be closed here :)
