### ISSUE TITLE
Flatten component flag is disabled

### ISSUE THREAD

**Issue by RosaWagner** [jenskutilek/homecomputer-fonts#4]
Is there a particular reason to disable it ? 
We prefer to avoid nested components because of poor support from post script printers, so I would recommend to enable the flag if it is fine by you.

**Comment by jenskutilek** [comment]
Yes, there is a reason: Because all glyphs are made of a small set of "pixel" components, flattening them would cause the file size to increase, because all accented glyphs would gain a large number of components from their respective base glyphs.

But the effect seems to be not as bad as I expected. The Sixtyfour TTF for example would go from 59 kB to 64 kB, with no perceptible difference in the woff2 size.

**Comment by jenskutilek** [comment]
I've updated the settings in 49c126fd381dd67f49bb70df89507fd2a2f4effb.
